---
language: python
python: "2.7"

before_install:

    - sudo apt-get update
    - sudo apt-get -y upgrade
    - sudo apt-get -y autoremove
    - sudo apt-get -y clean

    # Remove MySQL and Java
    - sudo apt-get -y purge '.*mysql.*' '.*jdk.*' '.*jre.*' '.*java.*'
    - sudo apt-get -y autoremove
    - sudo apt-get -y autoclean
    - sudo rm -rf /var/lib/mysql
    - sudo truncate -s 0 /var/log/mysql/error.log


install:

    # Install Ansible.
    - sudo pip install --upgrade ansible
    - ansible-playbook --version

    # Install required roles.
    - ansible-playbook -i travis/inventory getroles.yml 

script:

    # Check the role/playbook's syntax.
    - ansible-playbook -i travis/inventory site.yml --syntax-check

    # Run the role/playbook with ansible-playbook.
    - ansible-playbook -i travis/inventory site.yml

    # Idempotence Test
    - >
      ansible-playbook -i travis/inventory site.yml
      | grep -q 'changed=1 .*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

    # FIXME: send some mail and confirm delivery
